# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# use to compile GUI file: pyuic5 -x cookGUI.ui -o cookGUI.py

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1109, 696)
        Dialog.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-40, -40, 1241, 811))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(70, 650, 231, 51))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-color: rgb(0, 170, 0);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 650, 231, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-color: rgb(0, 170, 0);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 650, 231, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-color: rgb(0, 170, 0);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(890, 650, 231, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-color: rgb(0, 170, 0);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 0);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Done"))
        self.pushButton_2.setText(_translate("Dialog", "Done"))
        self.pushButton_3.setText(_translate("Dialog", "Done"))
        self.pushButton_4.setText(_translate("Dialog", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
