# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\edit_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_Dialog(object):
    def setupUi(self, edit_Dialog):
        edit_Dialog.setObjectName("edit_Dialog")
        edit_Dialog.resize(589, 327)
        self.buttonBox = QtWidgets.QDialogButtonBox(edit_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 290, 341, 32))
        self.buttonBox.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(edit_Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 80, 451, 182))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.description_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.description_label.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 1, 0, 1, 1)
        self.itemName_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.itemName_label.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.itemName_label.setObjectName("itemName_label")
        self.gridLayout.addWidget(self.itemName_label, 0, 0, 1, 1)
        self.price_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.price_label.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.price_label.setObjectName("price_label")
        self.gridLayout.addWidget(self.price_label, 2, 0, 1, 1)
        self.image_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.image_label.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 3, 0, 1, 1)
        self.itemName_plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.itemName_plainTextEdit.setMaximumSize(QtCore.QSize(16777214, 36))
        self.itemName_plainTextEdit.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.itemName_plainTextEdit.setObjectName("itemName_plainTextEdit")
        self.gridLayout.addWidget(self.itemName_plainTextEdit, 0, 1, 1, 1)
        self.description_plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.description_plainTextEdit.setMaximumSize(QtCore.QSize(16777214, 60))
        self.description_plainTextEdit.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.description_plainTextEdit.setObjectName("description_plainTextEdit")
        self.gridLayout.addWidget(self.description_plainTextEdit, 1, 1, 1, 1)
        self.price_plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.price_plainTextEdit.setMaximumSize(QtCore.QSize(16777214, 36))
        self.price_plainTextEdit.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.price_plainTextEdit.setObjectName("price_plainTextEdit")
        self.gridLayout.addWidget(self.price_plainTextEdit, 2, 1, 1, 1)
        self.image_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.image_pushButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.image_pushButton.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.image_pushButton.setObjectName("image_pushButton")
        self.gridLayout.addWidget(self.image_pushButton, 3, 1, 1, 1)
        self.title_label = QtWidgets.QLabel(edit_Dialog)
        self.title_label.setGeometry(QtCore.QRect(50, 40, 81, 16))
        self.title_label.setObjectName("title_label")

        self.retranslateUi(edit_Dialog)
        self.buttonBox.accepted.connect(edit_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(edit_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(edit_Dialog)

    def retranslateUi(self, edit_Dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_Dialog.setWindowTitle(_translate("edit_Dialog", "Edit Menu Item"))
        self.description_label.setText(_translate("edit_Dialog", "Description:"))
        self.itemName_label.setText(_translate("edit_Dialog", "Item Name:"))
        self.price_label.setText(_translate("edit_Dialog", "Price:"))
        self.image_label.setText(_translate("edit_Dialog", "Image:"))
        self.image_pushButton.setText(_translate("edit_Dialog", "Choose Image"))
        self.title_label.setText(_translate("edit_Dialog", "Edit Menu Item:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_Dialog = QtWidgets.QDialog()
    ui = Ui_edit_Dialog()
    ui.setupUi(edit_Dialog)
    edit_Dialog.show()
    sys.exit(app.exec_())
