# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'managerOrderListGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.orderList_View = QtWidgets.QListView(self.centralwidget)
        self.orderList_View.setGeometry(QtCore.QRect(40, 50, 256, 471))
        self.orderList_View.setObjectName("orderList_View")
        self.editOrder_but = QtWidgets.QPushButton(self.centralwidget)
        self.editOrder_but.setGeometry(QtCore.QRect(440, 100, 271, 101))
        self.editOrder_but.setObjectName("editOrder_but")
        self.voidOrder_but = QtWidgets.QPushButton(self.centralwidget)
        self.voidOrder_but.setGeometry(QtCore.QRect(440, 340, 271, 101))
        self.voidOrder_but.setObjectName("voidOrder_but")
        self.manageOrderList_label = QtWidgets.QLabel(self.centralwidget)
        self.manageOrderList_label.setGeometry(QtCore.QRect(40, 10, 251, 41))
        self.manageOrderList_label.setAlignment(QtCore.Qt.AlignCenter)
        self.manageOrderList_label.setObjectName("manageOrderList_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.editOrder_but.setText(_translate("MainWindow", "EDIT ORDER"))
        self.voidOrder_but.setText(_translate("MainWindow", "VOID ORDER"))
        self.manageOrderList_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Order #foo</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
