# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\managerGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manager_QWidget(object):
    def setupUi(self, manager_QWidget):
        manager_QWidget.setObjectName("manager_QWidget")
        manager_QWidget.resize(567, 506)
        manager_QWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.menuItems_label = QtWidgets.QLabel(manager_QWidget)
        self.menuItems_label.setGeometry(QtCore.QRect(40, 50, 151, 41))
        self.menuItems_label.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.menuItems_label.setObjectName("menuItems_label")
        self.addItem_pushButton = QtWidgets.QPushButton(manager_QWidget)
        self.addItem_pushButton.setGeometry(QtCore.QRect(40, 430, 121, 31))
        self.addItem_pushButton.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.addItem_pushButton.setObjectName("addItem_pushButton")
        self.editItem_pushButton = QtWidgets.QPushButton(manager_QWidget)
        self.editItem_pushButton.setGeometry(QtCore.QRect(210, 430, 121, 31))
        self.editItem_pushButton.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.editItem_pushButton.setObjectName("editItem_pushButton")
        self.removeItem_pushButton = QtWidgets.QPushButton(manager_QWidget)
        self.removeItem_pushButton.setGeometry(QtCore.QRect(400, 430, 121, 31))
        self.removeItem_pushButton.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.removeItem_pushButton.setObjectName("removeItem_pushButton")
        self.menuItems_tableView = QtWidgets.QTableView(manager_QWidget)
        self.menuItems_tableView.setGeometry(QtCore.QRect(40, 110, 491, 211))
        self.menuItems_tableView.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.menuItems_tableView.setObjectName("menuItems_tableView")

        self.retranslateUi(manager_QWidget)
        QtCore.QMetaObject.connectSlotsByName(manager_QWidget)

    def retranslateUi(self, manager_QWidget):
        _translate = QtCore.QCoreApplication.translate
        manager_QWidget.setWindowTitle(_translate("manager_QWidget", "Form"))
        self.menuItems_label.setText(_translate("manager_QWidget", "Menu Items"))
        self.addItem_pushButton.setText(_translate("manager_QWidget", "Add Item"))
        self.editItem_pushButton.setText(_translate("manager_QWidget", "Edit Item"))
        self.removeItem_pushButton.setText(_translate("manager_QWidget", "Remove Item"))
        self.menuItems_tableView.setWhatsThis(_translate("manager_QWidget", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    manager_QWidget = QtWidgets.QWidget()
    ui = Ui_manager_QWidget()
    ui.setupUi(manager_QWidget)
    manager_QWidget.show()
    sys.exit(app.exec_())
