# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 901)
        self.firstbackground = QtWidgets.QWidget(Dialog)
        self.firstbackground.setGeometry(QtCore.QRect(0, 0, 1601, 901))
        self.firstbackground.setStyleSheet("QWidget#firstbackground{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.449, x2:0, y2:1, stop:0.60199 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.firstbackground.setObjectName("firstbackground")
        self.welcometxt = QtWidgets.QLabel(self.firstbackground)
        self.welcometxt.setGeometry(QtCore.QRect(600, 50, 461, 151))
        self.welcometxt.setStyleSheet("color: rgb(255, 1, 1);\n"
"font: ;\n"
"font: 86pt \"Gabriola\";")
        self.welcometxt.setObjectName("welcometxt")
        self.createOrderbutton = QtWidgets.QPushButton(self.firstbackground)
        self.createOrderbutton.setGeometry(QtCore.QRect(970, 720, 381, 101))
        self.createOrderbutton.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);")
        self.createOrderbutton.setObjectName("createOrderbutton")
        self.label = QtWidgets.QLabel(self.firstbackground)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(520, 190, 561, 501))
        self.label.setStyleSheet("image: url(:/newPrefix/Los_Pollos.webp);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.manageOrder = QtWidgets.QPushButton(self.firstbackground)
        self.manageOrder.setGeometry(QtCore.QRect(250, 720, 381, 101))
        self.manageOrder.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);")
        self.manageOrder.setObjectName("manageOrder")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcometxt.setText(_translate("Dialog", "Welcome"))
        self.createOrderbutton.setText(_translate("Dialog", "Create New Order"))
        self.manageOrder.setText(_translate("Dialog", "Manage Order"))
import logosource


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
