# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finishOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_finishOrder(object):
    def setupUi(self, finishOrder):
        finishOrder.setObjectName("finishOrder")
        finishOrder.resize(1600, 900)
        finishOrder.setStyleSheet("QMainWindow#finishOrder{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.449, x2:0, y2:1, stop:0.60199 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(finishOrder)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topside = QtWidgets.QWidget(self.centralwidget)
        self.topside.setObjectName("topside")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topside)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftWidget = QtWidgets.QWidget(self.topside)
        self.leftWidget.setStyleSheet("QWidget#leftWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"}")
        self.leftWidget.setObjectName("leftWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orderHead = QtWidgets.QWidget(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderHead.sizePolicy().hasHeightForWidth())
        self.orderHead.setSizePolicy(sizePolicy)
        self.orderHead.setStyleSheet("border-bottom: 2px solid black;")
        self.orderHead.setObjectName("orderHead")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.orderHead)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.orderlbFrm = QtWidgets.QFrame(self.orderHead)
        self.orderlbFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.orderlbFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.orderlbFrm.setObjectName("orderlbFrm")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.orderlbFrm)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.orderLabel = QtWidgets.QLabel(self.orderlbFrm)
        self.orderLabel.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);\n"
"font: 26pt \"Arial\";")
        self.orderLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.orderLabel.setObjectName("orderLabel")
        self.horizontalLayout_5.addWidget(self.orderLabel)
        self.horizontalLayout_3.addWidget(self.orderlbFrm)
        self.ordernumfrm = QtWidgets.QFrame(self.orderHead)
        self.ordernumfrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ordernumfrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ordernumfrm.setObjectName("ordernumfrm")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ordernumfrm)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.orderNumLabel = QtWidgets.QLabel(self.ordernumfrm)
        self.orderNumLabel.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);\n"
"font: 26pt \"Arial\";")
        self.orderNumLabel.setObjectName("orderNumLabel")
        self.horizontalLayout_4.addWidget(self.orderNumLabel)
        self.horizontalLayout_3.addWidget(self.ordernumfrm)
        self.verticalLayout_2.addWidget(self.orderHead)
        self.orderLstWid = QtWidgets.QWidget(self.leftWidget)
        self.orderLstWid.setObjectName("orderLstWid")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.orderLstWid)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.orderLstLabel = QtWidgets.QLabel(self.orderLstWid)
        self.orderLstLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.orderLstLabel.setObjectName("orderLstLabel")
        self.horizontalLayout_6.addWidget(self.orderLstLabel)
        self.verticalLayout_2.addWidget(self.orderLstWid)
        self.horizontalLayout_2.addWidget(self.leftWidget)
        self.rightWidget = QtWidgets.QWidget(self.topside)
        self.rightWidget.setObjectName("rightWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rightWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.nameFrm = QtWidgets.QFrame(self.rightWidget)
        self.nameFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameFrm.setObjectName("nameFrm")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.nameFrm)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.nameLabel = QtWidgets.QLabel(self.nameFrm)
        self.nameLabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 26pt \"Forte\";")
        self.nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_8.addWidget(self.nameLabel)
        self.horizontalLayout_7.addWidget(self.nameFrm)
        self.inputNameFrm = QtWidgets.QFrame(self.rightWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNameFrm.sizePolicy().hasHeightForWidth())
        self.inputNameFrm.setSizePolicy(sizePolicy)
        self.inputNameFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputNameFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputNameFrm.setObjectName("inputNameFrm")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.inputNameFrm)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.inputNameLineEdit = QtWidgets.QLineEdit(self.inputNameFrm)
        self.inputNameLineEdit.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 26pt \"Forte\";")
        self.inputNameLineEdit.setObjectName("inputNameLineEdit")
        self.horizontalLayout_9.addWidget(self.inputNameLineEdit)
        self.horizontalLayout_7.addWidget(self.inputNameFrm, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.rightWidget)
        self.verticalLayout.addWidget(self.topside)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget_2)
        finishOrder.setCentralWidget(self.centralwidget)

        self.retranslateUi(finishOrder)
        QtCore.QMetaObject.connectSlotsByName(finishOrder)

    def retranslateUi(self, finishOrder):
        _translate = QtCore.QCoreApplication.translate
        finishOrder.setWindowTitle(_translate("finishOrder", "MainWindow"))
        self.orderLabel.setText(_translate("finishOrder", "Order: "))
        self.orderNumLabel.setText(_translate("finishOrder", "00"))
        self.orderLstLabel.setText(_translate("finishOrder", "TextLabel"))
        self.nameLabel.setText(_translate("finishOrder", "Name:"))
        self.pushButton_2.setText(_translate("finishOrder", "Back"))
        self.pushButton.setText(_translate("finishOrder", "Submit Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    finishOrder = QtWidgets.QMainWindow()
    ui = Ui_finishOrder()
    ui.setupUi(finishOrder)
    finishOrder.show()
    sys.exit(app.exec_())
